{% set name = "PyInquirer" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c9a92d68d7727fbd886a7908c08fd9e9773e5dc211bf5cbf836ba90d366dee51


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - prompt_toolkit ==1.0.14
    - Pygments >=2.2.0
    - regex >=2016.11.21

test:
  imports:
    - PyInquirer
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/CITGuru/PyInquirer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyInquirer is a collection of common interactive command line user interfaces.

  description: |
    PyInquirer is a collection of common interactive command line user interfaces.
  doc_url: https://github.com/CITGuru/PyInquirer#documentation
  dev_url: https://github.com/CITGuru/PyInquirer

extra:
  recipe-maintainers:
    - apeltzer
    - ewels
